#!/bin/sh
./MachineReassignment typeSearch=2 instance=b_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a1_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=a2_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=b_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=2 instance=x_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=1
./MachineReassignment typeSearch=1 instance=a1_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a1_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a1_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a1_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a1_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a2_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a2_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a2_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a2_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=a2_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=b_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=1 instance=x_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=1
./MachineReassignment typeSearch=3 instance=a1_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a1_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a1_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a1_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a1_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a2_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a2_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a2_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a2_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=a2_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=b_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=3 instance=x_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=1
./MachineReassignment typeSearch=2 instance=a1_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a1_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=a2_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=b_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=2 instance=x_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=2
./MachineReassignment typeSearch=1 instance=a1_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a1_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a1_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a1_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a1_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a2_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a2_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a2_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a2_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=a2_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=b_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=1 instance=x_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=2
./MachineReassignment typeSearch=3 instance=a1_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a1_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a1_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a1_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a1_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a2_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a2_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a2_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a2_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=a2_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=b_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=3 instance=x_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=2
./MachineReassignment typeSearch=2 instance=a1_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a1_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=a2_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=b_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=2 instance=x_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=3
./MachineReassignment typeSearch=1 instance=a1_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a1_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a1_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a1_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a1_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a2_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a2_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a2_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a2_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=a2_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=b_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=1 instance=x_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=3
./MachineReassignment typeSearch=3 instance=a1_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a1_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a1_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a1_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a1_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a2_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a2_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a2_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a2_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=a2_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=b_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=3 instance=x_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=3
./MachineReassignment typeSearch=2 instance=a1_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a1_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=a2_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=b_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=2 instance=x_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=4
./MachineReassignment typeSearch=1 instance=a1_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a1_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a1_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a1_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a1_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a2_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a2_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a2_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a2_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=a2_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=b_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=1 instance=x_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=4
./MachineReassignment typeSearch=3 instance=a1_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a1_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a1_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a1_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a1_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a2_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a2_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a2_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a2_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=a2_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=b_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=3 instance=x_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=4
./MachineReassignment typeSearch=2 instance=a1_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_1 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_2 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_3 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_4 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_5 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_6 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_7 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_8 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_9 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_10 test=004 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_1 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_2 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_3 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_4 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_5 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_6 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_7 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_8 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_9 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_10 test=003 selectProcesses=3 subProblemSizeInit=4 subProblemSizeMax=100 pctRandom=0.2 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_1 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_2 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_3 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_4 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_5 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_6 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_7 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_8 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_9 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_10 test=002 selectProcesses=2 subProblemSizeInit=4 subProblemSizeMax=100 pctChangeMachine=0.3 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a1_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=a2_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=b_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_1 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_2 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_3 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_4 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_5 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_6 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_7 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_8 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_9 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=2 instance=x_10 test=001 selectProcesses=1 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 discrepancyMax=5 seed=5
./MachineReassignment typeSearch=1 instance=a1_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a1_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a1_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a1_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a1_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a2_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a2_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a2_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a2_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=a2_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=b_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_1 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_2 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_3 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_4 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_5 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_6 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_7 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_8 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_9 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=1 instance=x_10 test=005 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 seed=5
./MachineReassignment typeSearch=3 instance=a1_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a1_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a1_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a1_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a1_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a2_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a2_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a2_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a2_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=a2_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=b_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_1 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_2 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_3 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_4 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_5 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_6 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_7 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_8 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_9 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5
./MachineReassignment typeSearch=3 instance=x_10 test=006 selectProcesses=4 subProblemSizeInit=4 subProblemSizeMax=100 runTime=300 failuresMax=400 fatorFailuresMax=1.5 failuresinitialMax=31 topValueSeletion=3 topVariableSeletion=3 seed=5